import 'zone.js';
import '@angular/compiler';
import {Component} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
interface Product {id:number;name:string;category:string;price:number;detail:string;symbol:string;color:string;tag?:string;}
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],template:`
<header><a class="brand" href="./"><span class="brandmark">ϟ</span>quickstop<span class="brand-dot">.</span></a><span class="header-caption">A little stop. A better day.</span><button class="cart-button" (click)="cartOpen=!cartOpen">Your bag <span>{{count}}</span></button></header>
<div class="storebar"><div><span class="pin">⌖</span><strong>Pickup at</strong> <select aria-label="Pickup store" [(ngModel)]="store"><option>Oak Street · Dallas</option><option>Lakeview · Denton</option><option>Main Street · Austin</option></select></div><span>Sample stores · Ready in ~15 min</span></div>
<main><div class="shop"><section class="intro"><div><span class="eyebrow">YOUR EVERYDAY PIT STOP</span><h1>Good things.<br>On your way.</h1><p>Coffee, a quick bite, and all your favorites.<br>Pick your essentials. We’ll have them ready.</p><a href="#products" class="browse">Find your favorites ↓</a></div><div class="feature"><img src="breakfast.jpg" alt="Coffee and croissant on a table"><div class="feature-caption"><span>MORNING, SORTED.</span><strong>Your daily pick-me-up.</strong><small>Coffee & bakery favorites</small></div></div></section>
<section id="products"><div class="section-heading"><div><span class="eyebrow">GRAB. GO. ENJOY.</span><h2>What are you craving?</h2></div><span>{{filtered.length}} favorites</span></div><div class="searchrow"><label class="search"><span>⌕</span><input [(ngModel)]="query" placeholder="Search coffee, snacks, and more…" aria-label="Search products"><button *ngIf="query" (click)="query=''" aria-label="Clear search">×</button></label><select aria-label="Sort products" [(ngModel)]="sort"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><nav class="categories" aria-label="Product categories"><button *ngFor="let c of categories" [class.active]="category===c" (click)="category=c">{{c}}</button></nav>
<div class="grid"><article class="product" *ngFor="let p of filtered"><div class="product-art" [style.background]="p.color"><span class="product-tag" *ngIf="p.tag">{{p.tag}}</span><span class="symbol" role="img" [attr.aria-label]="p.name">{{p.symbol}}</span><span class="art-label">QUICKSTOP / {{p.category.toUpperCase()}}</span></div><div class="product-info"><small>{{p.category}}</small><h3>{{p.name}}</h3><p>{{p.detail}}</p><div class="product-bottom"><strong>{{p.price | currency}}</strong><button (click)="add(p)" [attr.aria-label]="'Add '+p.name+' to bag'">+</button></div></div></article></div><div class="empty-results" *ngIf="!filtered.length"><h3>No favorites found.</h3><p>Try a different search or category.</p><button (click)="query='';category='All favorites'">Reset filters</button></div></section></div>
<aside [class.mobile-open]="cartOpen"><div class="bag-heading"><h2>Your bag <span>{{count}}</span></h2><button class="close" (click)="cartOpen=false" aria-label="Close bag">×</button></div><div *ngIf="!count" class="bag-empty"><span>＋</span><h3>A good day starts here.</h3><p>Add something you love.<br>We’ll save your spot in line.</p></div><div class="cart-items"><div *ngFor="let line of lines" class="cart-line"><span class="cart-symbol" [style.background]="line.p.color">{{line.p.symbol}}</span><div><strong>{{line.p.name}}</strong><small>{{line.p.price | currency}}</small><div class="quantity"><button (click)="change(line.p.id,-1)" [attr.aria-label]="'Decrease '+line.p.name">−</button><span>{{line.qty}}</span><button (click)="add(line.p)" [attr.aria-label]="'Increase '+line.p.name">+</button><button class="remove" (click)="remove(line.p.id)" [attr.aria-label]="'Remove '+line.p.name">Remove</button></div></div></div></div><div class="totals"><div><span>Subtotal</span><span>{{subtotal | currency}}</span></div><div><span>Estimated tax (8.25%)</span><span>{{tax | currency}}</span></div><div class="total"><strong>Total</strong><strong>{{subtotal+tax | currency}}</strong></div></div><button class="checkout" [disabled]="!count" (click)="checkoutOpen=true;cartOpen=false">Continue to pickup</button><p class="bag-note">No delivery fees. Just grab and go.</p><div class="demo-note"><strong>Made for the portfolio.</strong><p>Independent Angular demo by Sai Manohar Nelluri. Sample products and stores. No payment or real orders.</p></div></aside></main>
<footer><span class="brand">quickstop.</span><span>Independent portfolio project · Not affiliated with 7‑Eleven</span><a href="https://unsplash.com/photos/fCUHx-iVGBE" target="_blank" rel="noopener">Photo: Fajar Imani Firdaus / Unsplash</a></footer><div class="toast" role="status" *ngIf="toast">{{toast}}</div>
<div class="overlay" *ngIf="checkoutOpen || success"><section class="modal" role="dialog" aria-modal="true" [attr.aria-label]="success ? 'Demo order confirmed' : 'Pickup checkout'"><button class="modal-close" (click)="checkoutOpen=false;success=false" aria-label="Close checkout">×</button><ng-container *ngIf="!success"><span class="eyebrow">ONE LAST STOP</span><h2>Make it a pickup.</h2><p>{{store}} · {{count}} items · {{subtotal+tax | currency}}</p><form #f="ngForm" (ngSubmit)="confirm(f.valid)"><label>Your name<input name="name" [(ngModel)]="name" required minlength="2" autocomplete="name" #n="ngModel"></label><small class="error" *ngIf="n.invalid && (n.touched || submitted)">Enter your name (at least 2 characters).</small><label>Email address<input name="email" type="email" [(ngModel)]="email" required email autocomplete="email" #e="ngModel"></label><small class="error" *ngIf="e.invalid && (e.touched || submitted)">Enter a valid email address.</small><label>Pickup time<select name="time" [(ngModel)]="time"><option>ASAP · approximately 15 minutes</option><option>In 30 minutes</option><option>In 1 hour</option></select></label><div class="checkout-summary"><span>Demo order total</span><strong>{{subtotal+tax | currency}}</strong></div><p class="privacy">Demo only. Your details are not sent or stored. No payment required.</p><button class="checkout" type="submit">Place demo order</button></form></ng-container><ng-container *ngIf="success"><div class="success-mark">✓</div><span class="eyebrow">LOOKS LIKE A GOOD DAY</span><h2>You’re all set, {{name}}.</h2><p>Demo order {{orderId}} is confirmed.</p><div class="confirmation"><strong>{{store}}</strong><span>{{time}}</span><span>{{orderCount}} items · {{orderTotal | currency}}</span></div><p>This is a simulated confirmation. No order was sent to a store.</p><button class="checkout" (click)="success=false;name='';email=''">Keep browsing</button></ng-container></section></div>
`})
class App {
products:Product[]=[
{id:1,name:'House blend coffee',category:'Coffee & drinks',price:2.49,detail:'Freshly brewed · 16 fl oz',symbol:'☕',color:'#f2e6d6',tag:'DAILY FAVORITE'},
{id:2,name:'Butter croissant',category:'Fresh bites',price:2.99,detail:'Flaky, golden, baked fresh',symbol:'🥐',color:'#ffebcd',tag:'FRESH PICK'},
{id:3,name:'Turkey club sandwich',category:'Fresh bites',price:6.49,detail:'Turkey, lettuce & tomato',symbol:'🥪',color:'#e8eedc'},
{id:4,name:'Iced matcha latte',category:'Coffee & drinks',price:4.29,detail:'Creamy oat milk · 16 fl oz',symbol:'🍵',color:'#e2eddf',tag:'TRY SOMETHING NEW'},
{id:5,name:'Sea salt potato chips',category:'Snacks',price:2.19,detail:'Classic crunch · 2.5 oz',symbol:'🥔',color:'#f4e6bf'},
{id:6,name:'Sparkling lemon water',category:'Coffee & drinks',price:1.89,detail:'Bright & bubbly · 12 fl oz',symbol:'🍋',color:'#f2f0ca'},
{id:7,name:'Chocolate chip cookie',category:'Snacks',price:1.79,detail:'Soft center, chocolate chunks',symbol:'🍪',color:'#eee0d6'},
{id:8,name:'Fresh banana',category:'Essentials',price:0.79,detail:'A little energy on the go',symbol:'🍌',color:'#fbefd4'},
{id:9,name:'Whole milk',category:'Essentials',price:3.49,detail:'Cold & fresh · 32 fl oz',symbol:'🥛',color:'#e1eafa'}];
categories=['All favorites','Coffee & drinks','Fresh bites','Snacks','Essentials'];category='All favorites';query='';sort='featured';store='Oak Street · Dallas';cart:Record<number,number>={};cartOpen=false;checkoutOpen=false;success=false;toast='';name='';email='';time='ASAP · approximately 15 minutes';submitted=false;orderId='';orderCount=0;orderTotal=0;timer:any;
get filtered(){let a=this.products.filter(p=>(this.category==='All favorites'||p.category===this.category)&&(p.name+' '+p.detail).toLowerCase().includes(this.query.trim().toLowerCase()));return this.sort==='featured'?a:a.sort((a,b)=>this.sort==='low'?a.price-b.price:b.price-a.price);}
get lines(){return this.products.filter(p=>this.cart[p.id]).map(p=>({p,qty:this.cart[p.id]}));}get count(){return Object.values(this.cart).reduce((a,b)=>a+b,0);}get subtotal(){return this.lines.reduce((a,l)=>a+l.p.price*l.qty,0);}get tax(){return Math.round(this.subtotal*0.0825*100)/100;}
add(p:Product){if((this.cart[p.id]||0)>=20){this.notify('Maximum 20 of each item.');return;}this.cart={...this.cart,[p.id]:(this.cart[p.id]||0)+1};this.notify(p.name+' added to your bag');}
change(id:number,n:number){const v=(this.cart[id]||0)+n;if(v<=0)this.remove(id);else this.cart={...this.cart,[id]:v};}remove(id:number){const c={...this.cart};delete c[id];this.cart=c;}notify(t:string){this.toast=t;clearTimeout(this.timer);this.timer=setTimeout(()=>this.toast='',2400);}
confirm(valid:boolean|null){this.submitted=true;if(!valid||!this.count)return;this.orderCount=this.count;this.orderTotal=this.subtotal+this.tax;this.orderId='QS-'+Math.random().toString(36).slice(2,7).toUpperCase();this.cart={};this.checkoutOpen=false;this.success=true;this.submitted=false;}
constructor(){const context=(document as any).modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'add_products_to_bag',description:'Add sample products to the visible shopping bag.',inputSchema:{type:'object',properties:{productIds:{type:'array',items:{type:'integer'},minItems:1,maxItems:20}},required:['productIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:any)=>{if(!Array.isArray(input?.productIds)||!input.productIds.length||input.productIds.length>20||input.productIds.some((id:any)=>!Number.isInteger(id)||!this.products.some(p=>p.id===id)))throw Error('Provide 1–20 valid product IDs.');for(const id of input.productIds)this.add(this.products.find(p=>p.id===id)!);return {itemCount:this.count,subtotal:this.subtotal};}})).catch(()=>{});}catch{}}}
}
bootstrapApplication(App).catch(console.error);
